jpa:
  open-in-view: false
  hibernate:
    ddl-auto: validate
  properties:
    hibernate:
      default_schema: ${POSTGRES_SCHEMA:public}
      jdbc:
        lob:
          non_contextual_creation: true

datasource:
  url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:task_manager}
  username: ${DB_USERNAME:postgres}
  password: ${DB_PASSWORD:postgres}
  driver-class-name: org.postgresql.Driver
liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml
  contexts: test